### PR TITLE
[Profiler] Timing information for each request

### PR DESCRIPTION
**Pull request by gregurco**
| Q                | A
| ---------------- | -----
| Bug fix          | no
| New feature      | yes
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | #202 
| License          | MIT

### CODE REVIEW

**Comment by gregurco** [comment]
@florianpreusner I also updated the image of the profiler from Readme, to show time  tracking of the requests: https://github.com/gregurco/EightPointsGuzzleBundle/tree/request_time_in_profiler#symfony-debug-toolbar--profiler
Is it good or do you have any ideas how to do it more informative?

**Comment by florianpreusner** [comment]
Really, really nice! 👏
Only small improvements can can be done (but also later in a different PR):
- maybe adding a icon at the beginning (a clock or stopwatch)
- maybe adding the option at which level(s) the time will switch color (default: 1 second)? So long requests will be displayed in orange/red. Can also help to log these kind of requests separately in a log file later

but to be honest: the current implementation is already a nice feature!

**Comment by gregurco** [comment]
@florianpreusner thank you for feedback :slightly_smiling_face: yep, I also had an idea about time separation, but I guess it should be somehow configurable. For some projects 1 sec request is ok, for another 1 sec is too much and so on :slightly_smiling_face:
Tomorrow I plan to test it on project and if it's OK, then I will merge.  Could you please reactivate checks from SensioLabsInsight? Then I will be able to merge it by myself.

**Comment by florianpreusner** [comment]
Yip 👍 
Reactivated SensioLabsInsight.

**Pull request merged**
