### PR TITLE
Allow guzzle 7

### PR DESCRIPTION
**Pull request by mihaileu**
| Q                | A
| ---------------- | -----
| Bug fix          | no
| New feature      | yes
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | [comma-separated list of tickets fixed by the PR, if any]
| License          | MIT

### CODE REVIEW

**Comment by gregurco** [comment]
Hello @mihaileu . Did you tested bundle with v7? Does it work well?

**Comment by mihaileu** [comment]
> Hello @mihaileu . Did you test bundle with v7? Does it work well?

I didn't tested it yet. I'll need to run some test but it might take some time. Also I'm not sure I'll cover all the features.

**Comment by gregurco** [comment]
I tested and it's ok :+1: Thanks!

**Comment by tjveldhuizen** [comment]
At which term can we expect a release containing this change? I'ld like to use Guzzle 7, however this bundle is blocking it.

**Comment by gregurco** [comment]
@tjveldhuizen thanks for reminder. Just released all changes: https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v8.2.0

**Pull request merged**
