### PR TITLE
Fixed guzzle version constraints and avoid old promises function API

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q                | A
| ---------------- | -----
| Bug fix          | yes
| New feature      | no
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | #325 and #327
| License          | MIT

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Test failures are unlreated. I can send a separate PR to fix that other broken test,

**Comment by gregurco** [comment]
@GrahamCampbell could you please rebase your branch to apply the fix?

**Comment by GrahamCampbell** [comment]
CI passing now.

**Comment by gregurco** [comment]
@GrahamCampbell thank you 👍

**Pull request merged**
