### PR TITLE
[Upgrade] Add info about upgrading From 7.x to 8.0

### PR DESCRIPTION
**Pull request by gregurco**
| Q                | A
| ---------------- | -----
| Bug fix          | no
| New feature      | no
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | -
| License          | MIT

### CODE REVIEW

**Comment by gabfr** [comment]
Hey @gregurco, what about shifting the PHP version to 7.2 since the 7.1 reached EOL?

**Comment by gregurco** [comment]
Hello @gabfr 
I know that PHP 7.1 reached EOL, but v8.0 of bundle will support SF 4.0, which requires at least PHP 7.1. From our side there are no reasons to restrict usage of PHP 7.1 - we don't receive any benefits by this restriction, but will cut a part of our users from this upgrade, event if they use SF 4.0.

Do you see any reasons to upgrade to PHP 7.2, besides EOL of this version?

**Comment by gabfr** [comment]
I see, you're right, SF 4.0 requires PHP 7.1. The only reason I had to shift it with some small fixes is because when I upgraded my application to SF 5 I faced some errors regarding the PHP version specification and some methods that conflicted the signature with the new version of the SF HttpKernel 5. This may cause some issues also when you start using SF 5 in your app.

Although, I think this can wait until SF 4 reach EOL also.

**Comment by gregurco** [comment]
@gabfr great :slightly_smiling_face: please report issues related to integration with SF 5 and we will try to resolve them.

**Pull request merged**
