### PR TITLE
Allow symfony 6 

### PR DESCRIPTION
**Pull request by b-vadym**
| Q                | A
| ---------------- | -----
| Bug fix          | no
| New feature      | no
| BC breaks        | no
| Deprecations     | no
| Tests pass       | no
| Fixed tickets    | 
| License          | MIT

Allow symfony 6 , psr/log 2|3.

### CODE REVIEW

**Comment by gregurco** [comment]
Seems good for me 👍  I managed to install it on Symfony 6 project and it worked.

@florianpreusner what about ci? I would like to see also CI build with different versions, but travis-ci.org doesn't work anymore. Could you migrate integration to travis-ci.com? I have no permission to do that.

**Review by gregurco — APPROVED** [review]

**Comment by b-vadym** [comment]
@gregurco GitHub CI report https://github.com/b-vadym/EightPointsGuzzleBundle/actions/runs/1763467492 .
Config https://github.com/b-vadym/EightPointsGuzzleBundle/blob/github-ci/.github/workflows/ci.yml

**Comment by gregurco** [comment]
@b-vadym thank you! I merged all changes, but I will release them tomorrow. Also probably I will reuse your github workflow config. Tomorrow I will test how does it work and probably will replace travis by github actions.

**Comment by florianpreusner** [comment]
Sorry for my late response, didn't get the notification (fixed now). Thanks for your contribution @b-vadym 🙏 
Idea of using GitHub actions for CI sounds good 👍

**Pull request merged**
