### PR TITLE
Add `symfony/asset` in debug mode

### LINKED ISSUE #293: Profiler crashes when `symfony/asset` is not available
| Q                | A
| ---------------- | -----
| Symfony version  | 5.0.3
| Bundle version   | 8.0.0

## Possible solution

* remove sole dependency on `{{ asset() }}` from codebase

## What?

When installing this bundle on Symfony 5 it needs `symfony/asset` when running in `debug` mode.

image

Related `composer.json` require sections:

```json
    "require": {
        "php": ">=7.3",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-dom": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "ext-json": "*",
        "eightpoints/guzzle-bundle": "^8.0",
        "league/fractal": "^0.18",
        "nelmio/api-doc-bundle": "dev-master",
        "nelmio/cors-bundle": "^2.0",
        "roave/security-advisories": "dev-master",
        "symfony/apache-pack": "^1.0",
        "symfony/console": "*",
        "symfony/dotenv": "*",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "*",
        "symfony/intl": "*",
        "symfony/monolog-bundle": "^3.4",
        "symfony/orm-pack": "^1.0",
        "symfony/panther": "^0.6.0",
        "symfony/security-bundle": "*",
        "symfony/web-link": "*",
        "symfony/yaml": "*",
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "liip/test-fixtures-bundle": "^1.3",
        "symfony/asset": "5.0.*",
        "symfony/profiler-pack": "^1.0",
        "symfony/test-pack": "^1.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "5.0.*"
        },
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
```

### PR DESCRIPTION
**Pull request by rvanlaak**
| Q                | A
| ---------------- | -----
| Bug fix          | yes
| New feature      | no
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | #293 
| License          | MIT

fixes #293

### CODE REVIEW

**Comment by gregurco** [comment]
Hello @rvanlaak
Thanks for issue and PR, but do you know, that when you install packages, the "require-dev" section from packages are totally ignored. "require-dev" are installed only while you are developing it - so if you clone the bundle and run `composer install` in the root of bundle folder. Do you think that this change will add assets package in your project? I think there are two options: either to add "symfony/asset" in "require" or to add message that package "symfony/asset" should be installed.

Could you please check and confirm that your PR works or another way is required?

**Comment by rvanlaak** [comment]
Can you elaborate on what you mean with `require-dev` packages are being ignored? Afaik dev dependencies only will be ignored when running `composer install --no-dev`.

After running `composer require --dev symfony/asset` the error from the screenshot was gone. The message you are proposing wouldn't solve the problem, as the error then still would be there. And, the error as given in the screenshot also is clear on that the package is missing.

**Comment by gregurco** [comment]
> After running composer require --dev symfony/asset the error from the screenshot was gone.
- yes, because you installed this package in your project. Now try to remove it and install your fork. You will see, that assets packages is not installed.

> Can you elaborate on what you mean with require-dev packages are being ignored?
described here: https://getcomposer.org/doc/04-schema.md#require-dev
and here: https://github.com/composer/composer/issues/1763#issuecomment-15825444

**Comment by gregurco** [comment]
@rvanlaak also check this PR: #257 The discussion was not finished, but there are a lot of links and explanations.

**Comment by rvanlaak** [comment]
Thank you for pointing to #257 , did read through the discussions and agree this PR should get closed[ as `require-dev` indeed is `root-only`](https://getcomposer.org/doc/04-schema.md#require-dev).

A better option would be to remove the sole `{{ asset() }}` usage this bundle has. What about a PR for that?

https://github.com/8p/EightPointsGuzzleBundle/search?q=asset&unscoped_q=asset

What you'd need is to add `symfony/twig-bridge` to the userland `require-dev` section when this bundle gets installed, but I'm not sure how to achieve that. Would it be possible to do that via [`pre-package-install`](https://getcomposer.org/doc/articles/scripts.md#package-events)?

```json
"scripts": {
    "pre-package-install": "composer require --dev symfony/web-profiler-bundle"
},
```

**Comment by gregurco** [comment]
I think for user it will be not obvious why 2 packages are installed instead of 1. Also I'm not sure if we can remove usage of `assets`. Need to check that.
I think there is no problem, because you receive this error just when open profiler and message is very descriptive. There is no unexpected crash and user has to waste few hours to understand it.
Finally we can add this package to [suggest](https://getcomposer.org/doc/04-schema.md#suggest) section with message that "install this package, if plan to use profiler".
What do you think? You went through this problem recently.

**Comment by rvanlaak** [comment]
The confusing part in the experience I had is that the profiler already crashes on the initial profiler search page (as the panel already gets required over there). Took me a while to figure out this had to do with this bundle.

As `symfony/asset` isn't required via `web-profiler-bundle` already that means it probably is easy to get rid of it 👍 Found out solving this is super simple after checking the way how `symfony/web-profiler-bundle` does solve this. Will file you another PR to resolve this in a few minutes.

**Comment by gregurco** [comment]
Great :+1:

**Comment by rvanlaak** [comment]
see #296 for other attempt on fixing #293

**Pull request closed without merging**
