### PR TITLE
Allow to configure curl options

### PR DESCRIPTION
**Pull request by gregurco**
- [ ] Bug fix
- [x] New feature
- [ ] BC breaks
- [ ] Deprecations
- [x] Tests pass

Fixed tickets: [#109]
Duplicates PR: [#103]
License: MIT

**TODO:**
- [x] functionality
- [ ] concept approve
- [x] tests
- [x] documentation

IMPORTANT: don't merge. It's not finished PR.

### CODE REVIEW

**Comment by gregurco** [comment]
@florianpreusner I added tests and changed Readme. So I think it's ready for code review. Please check and write if you have any remarks or suggestions :)

**Comment by gregurco** [comment]
@florianpreusner Fine. I think it meets the requirement of @scott-r-lindsey and can be merged

**Comment by florianpreusner** [comment]
Thanks, @gregurco!

**Comment by gregurco** [comment]
@florianpreusner you are welcome :) When do you plan to do new release?

**Comment by florianpreusner** [comment]
This week, Thursday: https://github.com/8p/EightPointsGuzzleBundle/milestones
The idea is to have the new features in master for a couple of days so some users can test. If there are no major issues I will release v7 on Thursday in the morning. 🎉

**Pull request merged**
