### PR TITLE
Add support of Symfony 5.x

### PR DESCRIPTION
**Pull request by gregurco**
| Q                | A
| ---------------- | -----
| Bug fix          | no
| New feature      | no
| BC breaks        | no
| Deprecations     | no
| Tests pass       | yes
| Fixed tickets    | -
| License          | MIT

### CODE REVIEW

**Comment by rpkamp** [comment]
The easiest way to solve supporting both Symfony 4.4 and Symfony 5.0 at the same time wrt the DataCollector is to use a Trait in the datacollector, and then use a different trait for Symfony 4.x than for 5.x.

Basically this: https://github.com/snc/SncRedisBundle/tree/master/DataCollector

**Comment by gregurco** [comment]
Thank you for idea, @rpkamp 
Interesting solution :slightly_smiling_face: we have something similar for events.

**Comment by mihaileu** [comment]
@gregurco what about a new tag ?

**Comment by mbadolato** [comment]
Would be nice to be able to pull these changes into a Symfony 5 project (currently possible with `dev-master` but would prefer a tag/release) 😄

**Comment by gregurco** [comment]
@mihaileu @mbadolato yep, the tag will appear soon :slightly_smiling_face: just few last changes before release.

**Pull request merged**
